services:
  marzban:
    container_name: marzban_panel
    image: gozargah/marzban:latest
    restart: always
    env_file: .env
    network_mode: host
    networks: # -------------------------------- set network
      - user_yasin
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - ./index.html:/code/app/templates/subscription/index.html
    expose:
      - "8000"

  nginx:
    container_name: marzban_nginx
    command: nginx -g 'daemon off;'
    depends_on:
      - marzban
    image: nginx:latest
    networks: # --------------------------------- set network
      - user_yasin
    ports:
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf


networks:
  user_yasin:
    name: user_yasin
    driver: host
