services:
  marzban:
    container_name: marzban_panel
    image: gozargah/marzban:latest
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - ./index.html:/code/app/templates/subscription/index.html
      - /etc/letsencrypt/live/sub.yasin-dev81.ir/fullchain.pem:/cert/fullchain.pem
      - /etc/letsencrypt/live/sub.yasin-dev81.ir/privkey.pem:/cert/key.pem
