services:
  marzban:
    container_name: marzban_panel_main
    image: gozargah/marzban:latest
    restart: always
    env_file: .env
    network_mode: host
    volumes:
      - /var/lib/marzban:/var/lib/marzban
      - ./index.html:/code/app/templates/subscription/index.html

  glass:
    container_name: marzban_glass_server
    image: wikihostinc/looking-glass-server:latest
    restart: always
    network_mode: host
    environment:
      - LISTEN_IP=0.0.0.0
      - HTTP_PORT=80
      - SPONSOR_MESSAGE=Powered by yasin-dev81.ir
      - SPEEDTEST_FILE_LIST=1MB 10MB 100MB
    depends_on:
      - marzban
